main = './cloud/resources/cloudflare/workers/request.ts'
compatibility_date = '2024-12-05'
compatibility_flags = [
  'nodejs_compat_v2'
]

[route]
  pattern = 'localhost:8080/*'
  zone_name = 'localhost'

[vars]
  AMPLITUDE_EXPERIMENTS = '[]'
  ENVIRONMENT = 'local'
  HOST = 'localhost'
