'$schema' = 'https://starship.rs/config-schema.json'
# command_timeout = 999999999
add_newline = true
format = """
$os\
$sudo\
$username\
$hostname\
$localip\
$gcloud\
$terraform\
$pulumi\
$kubernetes\
$helm\
$container\
$docker_context\
$package\
$python\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$character\
"""

# move the rest of the prompt to the right
right_format = """
$shell\
"""

[character]
  success_symbol = '[...](white)'
  error_symbol = '[...](white)'

[directory]
  repo_root_style = 'blue'
  format = '[$read_only]($read_only_style)[$path]($style) '
  truncate_to_repo = false
  truncation_length = 5
  style = 'black'

[docker_context]
  format = 'ğŸ³ '

[fill]
  style = 'white'

[gcloud]
  format = '(\($project?â˜ï¸  [$project](#1a73e8)\)) '

[git_branch]
  format = '([\($branch(:$remote_branch)\)](#f1502f) )'
  only_attached = true

[git_commit]
  format = '([\($hash$tag\)](#f1502f) )'
  tag_disabled = false

[git_status]
  format = '$stashed$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind'
  conflicted = '= '
  modified = ''
  ahead = '[â¬†](purple)  '
  behind = '[â¬‡](purple)  '
  diverged = '[â¬† â¬‡](purple)  '
  untracked = '[â–ªï¸](white) '
  deleted = '[âœ˜](bright-red) '
  renamed = '[Â»](yellow) '
  staged = '[+](yellow) '
  stashed = '[â­‘](yellow) '
  up_to_date = ''

[git_metrics]
  disabled = false
  format = '([$added](green)) ([$deleted](red)) '

[kubernetes]
  disabled = false
  format = 'âˆ [$context( \($namespace? \))](#09c1d1) '
  contexts = [
    { context_pattern = ".*_(.*)-(.*)_.*_(.*)" , context_alias = '${1}/${2}/${3}' }
  ]

[package]
  format = 'ğŸ“¦ [$version](white) '

[pulumi]
  format = 'ğŒ¤ [$stack](#be5188) '

[python]
  format = '[$symbol$pyenv_prefix($version )(\($virtualenv\) )](#f0cf3f)'

[shell]
  disabled = false

[sudo]
  disabled = false
  format = 'ğŸ‘» '

[time]
  disabled = false
  format = '[\[ $time \]](white) '
  time_format = '%m/%d %T'
