'$schema' = 'https://starship.rs/config-schema.json'

format = """
($os )\
($sudo )\
($username([@](#dddddd)$hostname)/)\
$directory\
$git_branch \
$git_commit\
$git_status\
$git_state\
$git_metrics\
$fill \
$swift\
$python\
$package\
$docker_context\
$container\
$helm\
$kubernetes\
$pulumi\
$terraform\
$gcloud\
"""

[directory]
  repo_root_style = 'blue'
  format = '[$read_only]($read_only_style)[$path]($style)'
  truncate_to_repo = false
  truncation_length = 5
  style = '#cccccc'
  repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$read_only]($read_only_style)\
[$path]($style)\
"""

[docker_context]
  format = ' ïŒˆ '

[fill]
  symbol = 'â¯'
  style = '#999999'

[gcloud]
  format = '( îŸ±  [$project](#1a73e8))'

[git_branch]
  format = ' [\($branch(:$remote_branch)\)](#f1502f)'
  only_attached = true

[git_commit]
  format = ' [\($hash($tagï€«)\)](#f1502f)'
  tag_disabled = false

[git_metrics]
  disabled = false
  format = """
([$added](green) )\
([$deleted](red) )\
"""

[git_state]
  format = '\([$state( $progress_current/$progress_total)]($style)\)'

[git_status]
  conflicted = '='
  modified = ''
  ahead = '[ï…¶](purple)'
  behind = '[ï…µ](purple)'
  diverged = '[ï…¶ï…µ](purple)'
  untracked = '[â–ªï¸](black)'
  deleted = '[âœ˜](bright-red)'
  renamed = '[â©ï¸](white)'
  staged = '[+](white)'
  stashed = '[â­‘](yellow)'
  up_to_date = ''
  format = """
($ahead_behind )\
($stashed )\
($conflicted )\
($deleted )\
($renamed)\
($modified )\
($staged )\
($untracked )\
"""

[hostname]
  format = '[$hostname]($style)'

[kubernetes]
  disabled = false
  format = " $symbol[$context(/$namespace)](#09c1d1)"

[lua]
  symbol = 'î˜  '

[nix_shell]
  symbol = 'ïŒ“ '

[os]
  # disabled = false

[os.symbols]
  Alpaquita = 'îª¢ '
  Alpine = 'ïŒ€ '
  AlmaLinux = 'ïŒ '
  Amazon = 'ï‰° '
  Android = 'ï…» '
  AOSC = 'ïŒ '
  Arch = 'ïŒƒ '
  Artix = 'ïŒŸ '
  CachyOS = 'ïŒƒ '
  CentOS = 'ïŒ„ '
  Debian = 'ïŒ† '
  DragonFly = 'îŠ '
  Emscripten = 'ïˆ… '
  EndeavourOS = 'ï†— '
  Fedora = 'ïŒŠ '
  FreeBSD = 'ïŒŒ '
  Garuda = 'ó°›“ '
  Gentoo = 'ïŒ '
  HardenedBSD = 'ó°Œ '
  Illumos = 'ó°ˆ¸ '
  Kali = 'ïŒ§ '
  Linux = 'ïŒš '
  Mabox = 'î¬© '
  Macos = 'ïŒ‚ '
  Manjaro = 'ïŒ’ '
  Mariner = 'ï‡ '
  MidnightBSD = 'ï†† '
  Mint = 'ïŒ '
  NetBSD = 'ï€¤ '
  NixOS = 'ïŒ“ '
  Nobara = 'ï€ '
  OpenBSD = 'ó°ˆº '
  openSUSE = 'ïŒ” '
  OracleLinux = 'ó°Œ· '
  Pop = 'ïŒª '
  Raspbian = 'ïŒ• '
  Redhat = 'ïŒ– '
  RedHatEnterprise = 'ïŒ– '
  RockyLinux = 'ïŒ« '
  Redox = 'ó°€˜ '
  Solus = 'ó° ³ '
  SUSE = 'ïŒ” '
  Ubuntu = 'ïŒ› '
  Unknown = 'ïˆ­ '
  Void = 'ïŒ® '
  Windows = 'ó°² '

[package]
  format = ' ğŸ“¦ [$version](white)'

[pulumi]
  format = ' ï” [$stack](#be5188)'

[shell]
  disabled = false

[sudo]
  disabled = false
  format = 'ğŸ‘»'

[username]
  format = '[$user]($style)'
