'$schema' = 'https://starship.rs/config-schema.json'
# command_timeout = 999999999
add_newline = true
format = """
$os\
$sudo\
$username\
$hostname\
$localip\
$directory\
"""

right_format = """
$git_metrics\
$git_status\
$git_state\
$git_commit\
$git_branch\
$swift\
$python\
$package\
$docker_context\
$container\
$helm\
$kubernetes\
$pulumi\
$terraform\
$gcloud\
"""

[character]
  format = '[â¯](white) '

[directory]
  repo_root_style = 'blue'
  format = '[$read_only]($read_only_style)[$path]($style) '
  truncate_to_repo = false
  truncation_length = 5
  style = 'black'

[docker_context]
  format = 'ğŸ³ '

[fill]
  symbol = ' '
  style = 'white'

[gcloud]
  format = '(â˜ï¸  [$project](#1a73e8) )'

[git_branch]
  format = '([\($branch(:$remote_branch)\)](#f1502f) )'
  only_attached = true

[git_commit]
  format = '([\($hash$tag\)](#f1502f) )'
  tag_disabled = false

[git_status]
  conflicted = '= '
  modified = ''
  ahead = '[â¬†](magenta)  '
  behind = '[â¬‡](magenta)  '
  diverged = '[â¬† â¬‡](magenta)  '
  untracked = '[â–ªï¸](white) '
  deleted = '[âœ˜](bright-red) '
  renamed = '[Â»](yellow) '
  staged = '[+](yellow) '
  stashed = '[â­‘](yellow) '
  up_to_date = ''
  format = """
$stashed\
$conflicted\
$deleted\
$renamed\
$modified\
$staged\
$untracked\
$ahead_behind\
"""

[git_metrics]
  disabled = false
  format = '([$added](green)) ([$deleted](red)) '

[kubernetes]
  disabled = false
  format = 'âˆ [$context \($namespace\)](#09c1d1) '
  contexts = [
    { context_pattern = ".*_(.*)-(.*)_.*_(.*)" , context_alias = '${1}/${2}/${3}' }
  ]

[package]
  format = 'ğŸ“¦ [$version](white) '

[pulumi]
  format = 'ğŒ¤ [$stack](#be5188) '

[python]
  format = '[$symbol$pyenv_prefix($version )(\($virtualenv\) )](#f0cf3f)'

[shell]
  disabled = false

[sudo]
  disabled = false
  format = 'ğŸ‘» '
