'$schema' = 'https://starship.rs/config-schema.json'
format = """
($os )\
($sudo )\
($username(@$hostname) )\
($directory )\
$fill\
$git_metrics\
$git_status\
$git_state\
$git_commit\
$git_branch\
$swift\
$python\
$package\
$docker_context\
$container\
$helm\
$kubernetes\
$pulumi\
$terraform\
$gcloud\
"""

[directory]
  repo_root_style = 'blue'
  format = '[$read_only]($read_only_style)[$path]($style)'
  repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$read_only]($read_only_style)\
[$path]($style)\
"""
  truncate_to_repo = false
  truncation_length = 5
  style = 'black'

[docker_context]
  format = ' ğŸ³'

[fill]
  symbol = '_'
  style = 'black'

[gcloud]
  format = '( â˜ï¸  [$project](#1a73e8))'

[git_branch]
  format = ' [\($branch(:$remote_branch)\)](#f1502f)'
  only_attached = true

[git_commit]
  format = ' [\($hash$tag\)](#f1502f)'
  tag_disabled = false

[git_metrics]
  disabled = false
  format = """
( [$added](green))\
( [$deleted](red))\
"""

[git_state]
  format = '\([$state( $progress_current/$progress_total)]($style)\)'

[git_status]
  conflicted = '='
  modified = ''
  ahead = '[â¬†](purple) '
  behind = '[â¬‡](purple) '
  diverged = '[â¬† â¬‡](purple) '
  untracked = '[â–ªï¸](white)'
  deleted = '[âœ˜](bright-red)'
  renamed = '[Â»](yellow)'
  staged = '[+](yellow)'
  stashed = '[â­‘](yellow)'
  up_to_date = ''
  format = """
( $stashed)\
( $conflicted)\
( $deleted)\
( $renamed)\
( $modified)\
( $staged)\
( $untracked)\
( $ahead_behind)\
"""

[hostname]
  format = '[$hostname]($style)'

[kubernetes]
  disabled = false
  format = ' âˆ [$context(/$namespace)](#09c1d1)'

[package]
  format = ' ğŸ“¦ [$version](white)'

[pulumi]
  format = ' ğŒ¤ [$stack](#be5188)'

[python]
  format = ' [$symbol$pyenv_prefix( $version)(\( $virtualenv\))](#f0cf3f)'

[shell]
  disabled = false

[sudo]
  disabled = false
  format = 'ğŸ‘»'

[username]
  format = '[$user]($style)'
